splitting: [0.8, 0.2]
channels: [1]
transformations:
  patch_size: [160, 200, 155]
  resize_shape: [32, 40, 32]
  elastic: false
  scaling: true
  rotation: true
  gaussian_noise: false
  gaussian_blur: false
  brightness: false
  contrast: false
  gamma: false
  mirror: false
  dummy_2D: false

batch_size: 4
n_train_timesteps: 1000
n_infer_timesteps: 1000
time_scheduler: "scaled_linear_beta"
n_epochs: 500
val_interval: 20
learning_rate: 5e-5

model_params:
  spatial_dims: 3
  in_channels: 1
  out_channels: 1
  num_channels: [128, 128, 256]
  attention_levels: [false, false, true]
  num_head_channels: [0, 0, 256]
  num_res_blocks: 2

progress_bar: True
output_mode: "verbose"
save_model: false
save_graph: false
save_plots: true
save_profile: false
