splitting: [0.8, 0.2]
channels: [1]
transformations:
  patch_size: [160, 200, 155]
  resize_shape: [64, 64 ,64]
  elastic: False
  scaling: true
  rotation: true
  gaussian_noise: False
  gaussian_blur: False
  brightness: False
  contrast: False
  gamma: False
  mirror: False
  dummy_2D: false

batch_size: 4
n_train_timesteps: 1000
n_infer_timesteps: 1000
time_scheduler: "scaled_linear_beta"
n_epochs: 150
val_interval: 5
learning_rate: 5e-5

model_params:
  spatial_dims: 3
  in_channels: 1
  out_channels: 1
  num_channels: [128, 128, 256]
  attention_levels: [false, false, true]
  num_head_channels: [0, 0, 256]
  num_res_blocks: 2

progress_bar: False
output_mode: "verbose"
save_model: false
save_graph: false
save_plots: true
save_profile: false

# for DecathlonDataset first run:
# export TMPDIR=/path_to_temp_dir
