center_crop_size: [160, 200, 155]
resized_size: [64, 64, 64]
batch_size: 1
n_train_timesteps: 1000
n_infer_timesteps: 1000
time_scheduler: "scaled_linear_beta"
n_epochs: 100
val_interval: 5
learning_rate: 5e-5

model_params:
  spatial_dims: 3
  in_channels: 1
  out_channels: 1
  num_channels: [64, 128, 256]
  attention_levels: [False, False, True]
  num_head_channels: [0, 0, 256]
  num_res_blocks: 2

output_mode: "verbose"
save_model: False
save_graph: False
save_plots: True
save_profile: False

# for DecathlonDataset first run:
# export TMPDIR=/path_to_temp_dir